# From https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution

apiVersion: v1
kind: Pod
metadata:
  name: netutils
spec:
  containers:
  - name: netutils
    image: ghcr.io/testdotcom/netutils:main
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
