name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate a config.json
      run: |
        cat <<JSON > config.json
        {
          "auths": {
            "${{ env.REGISTRY }}": {
              "auth": "$(echo -n :${{ secrets.GITHUB_TOKEN }} | base64)"
            }
          }
        }
        JSON
    - name: Build & push an image
      run: |
        docker run \
          -v $(pwd):/workspace \
          -v $(pwd)/config.json:/kaniko/.docker/config.json:ro \
          gcr.io/kaniko-project/executor:latest \
            --context dir:///workspace/ \
            --dockerfile Dockerfile \
            --cache=true \
            --cache-repo ${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY }}/${{ env.IMAGE_NAME }}-cache \
            --destination ${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
