name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@bea6a01aa40b4d58b0382d47e1c4a70137af67b1
      with:
        buildkitd-flags: --debug
    
    - name: Login Container registry
      uses: docker/login-action@21f251affc0769ccac8a1cf17e937592fb492337
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata for image
      id: meta
      uses: docker/metadata-action@59bc9ddfd5a31eb6f5b55e89b65578fe3bbba85e
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
    - name: Image build and push
      uses: docker/build-push-action@965c6a410d446a30e95d35052c67d6eded60dad6
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
